// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRw13irV7E7Hf9ZR0E-mtzAI0MiXZZRDU',
    appId: '1:745146958704:web:42ff60f129f3fdffd085b5',
    messagingSenderId: '745146958704',
    projectId: 'opd-management-6c33f',
    authDomain: 'opd-management-6c33f.firebaseapp.com',
    storageBucket: 'opd-management-6c33f.firebasestorage.app',
    measurementId: 'G-Z50ELDKRPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5G1zZZ4Mw037KzOh5_VGP2GRpFJoqv3E',
    appId: '1:745146958704:android:62d866107315e078d085b5',
    messagingSenderId: '745146958704',
    projectId: 'opd-management-6c33f',
    storageBucket: 'opd-management-6c33f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJaLMW2mQgl4vT2i8XF5O2gxDIbYrA-A',
    appId: '1:745146958704:ios:8ba67b46beb6da6ad085b5',
    messagingSenderId: '745146958704',
    projectId: 'opd-management-6c33f',
    storageBucket: 'opd-management-6c33f.firebasestorage.app',
    androidClientId: '745146958704-kob9q2gi1jf157b5cj4l7g3v9ak9kmv9.apps.googleusercontent.com',
    iosClientId: '745146958704-spset6kfijcqh4nulunlvtpd15htfc45.apps.googleusercontent.com',
    iosBundleId: 'in.primacura.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoJaLMW2mQgl4vT2i8XF5O2gxDIbYrA-A',
    appId: '1:745146958704:ios:c7c08e9f6627d0f7d085b5',
    messagingSenderId: '745146958704',
    projectId: 'opd-management-6c33f',
    storageBucket: 'opd-management-6c33f.appspot.com',
    iosBundleId: 'com.example.opdManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRw13irV7E7Hf9ZR0E-mtzAI0MiXZZRDU',
    appId: '1:745146958704:web:55ecb8fe9a886fccd085b5',
    messagingSenderId: '745146958704',
    projectId: 'opd-management-6c33f',
    authDomain: 'opd-management-6c33f.firebaseapp.com',
    storageBucket: 'opd-management-6c33f.appspot.com',
    measurementId: 'G-894X8TPBTL',
  );
}